package extractor

import (
	"archive/zip"
	"bytes"
	"compress/zlib"
	"context"
	"debug/elf"
	"encoding/binary"
	"strings"
	"testing"
)

// ─── Java extractor ────────────────────────────────────────────────

func TestJavaExtractorPomProperties(t *testing.T) {
	body := buildJAR(t, map[string]string{
		"META-INF/maven/org.apache.commons/commons-lang3/pom.properties": "" +
			"# Generated by Maven\n" +
			"version=3.14.0\n" +
			"groupId=org.apache.commons\n" +
			"artifactId=commons-lang3\n",
		"META-INF/MANIFEST.MF": "Manifest-Version: 1.0\r\n\r\n",
	})

	id, err := (&JavaExtractor{}).Extract(context.Background(), File{
		Path: "opt/lib/commons-lang3-3.14.0.jar",
		Body: body,
	})
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if id.Name != "commons-lang3" {
		t.Errorf("Name = %q", id.Name)
	}
	if id.Version != "3.14.0" {
		t.Errorf("Version = %q", id.Version)
	}
	if id.PURL != "pkg:maven/org.apache.commons/commons-lang3@3.14.0" {
		t.Errorf("PURL = %q", id.PURL)
	}
	if id.Properties["java.tier"] != "pom-properties" {
		t.Errorf("tier = %q", id.Properties["java.tier"])
	}
	if id.Vendor != "org.apache.commons" {
		t.Errorf("Vendor = %q", id.Vendor)
	}
}

func TestJavaExtractorManifestFallback(t *testing.T) {
	body := buildJAR(t, map[string]string{
		"META-INF/MANIFEST.MF": "Manifest-Version: 1.0\r\n" +
			"Implementation-Title: Apache Mina\r\n" +
			"Implementation-Version: 2.0.0\r\n" +
			"Implementation-Vendor: org.apache.mina\r\n\r\n",
	})

	id, err := (&JavaExtractor{}).Extract(context.Background(), File{
		Path: "opt/mina.jar",
		Body: body,
	})
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if id.Name != "Apache Mina" || id.Version != "2.0.0" {
		t.Errorf("identity = %+v", id)
	}
	if id.Properties["java.tier"] != "manifest" {
		t.Errorf("tier = %q", id.Properties["java.tier"])
	}
}

// S4 Task 0: the filename-pattern fallback was removed because a JAR
// named `commons-lang3-3.14.0.jar` with no manifest / no pom.properties
// is not a verifiable identity claim. JARs that fall past tiers 1 and 2
// now return empty Identity and the untracked enricher records them
// as observed-only.
func TestJavaExtractorNoFilenameFallback(t *testing.T) {
	body := buildJAR(t, nil)

	id, err := (&JavaExtractor{}).Extract(context.Background(), File{
		Path: "opt/lib/jq-1.7.0.jar",
		Body: body,
	})
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if !id.IsEmpty() {
		t.Errorf("Identity = %+v, want empty (filename fallback was removed)", id)
	}
}

func TestJavaExtractorMatchRequiresZipMagic(t *testing.T) {
	e := &JavaExtractor{}
	// Right extension, wrong magic → must not match.
	if e.Match(context.Background(), File{
		Path: "fake.jar",
		Body: []byte("not zip bytes"),
	}) {
		t.Error("Match should require zip magic, not just extension")
	}
}

// ─── Go extractor ───────────────────────────────────────────────────
//
// A real Go binary fixture would balloon repository size; we rely on
// the existing fingerprint-package tests for end-to-end Go buildinfo
// reads. Here we cover the wrapper's behaviour on inputs that ARE NOT
// Go binaries — which is the dominant runtime case.

func TestGoExtractorRejectsNonBinary(t *testing.T) {
	e := &GoExtractor{}
	if e.Match(context.Background(), File{Body: []byte("plain text")}) {
		t.Error("Match should reject non-binary bodies")
	}
}

func TestGoExtractorReturnsEmptyForBareELF(t *testing.T) {
	// An ELF file without buildinfo (synthesised below) must return
	// (empty, nil) so the registry falls through to the next
	// extractor.
	body := buildMinimalELF(t)
	id, err := (&GoExtractor{}).Extract(context.Background(), File{Body: body})
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if !id.IsEmpty() {
		t.Errorf("Identity = %+v, want empty (no buildinfo)", id)
	}
}

// S4 Task 1: Go module versions on the Component.Version field must
// have the leading `v` stripped (purl-spec golang type still requires
// `v` on the PURL, but every other ecosystem in the SBOM lists
// Version unprefixed and downstream tooling expects consistency).
// `(devel)` is preserved verbatim as a marker. Pseudo-versions and
// `+incompatible` suffixes are preserved verbatim after the `v`
// strip.
func TestCleanGoVersion(t *testing.T) {
	cases := map[string]string{
		"":                                       "",
		"(devel)":                                "(devel)",
		"v1.2.3":                                 "1.2.3",
		"v0.0.0-20231212003515-deadbeefcafe1234": "0.0.0-20231212003515-deadbeefcafe1234",
		"v28.5.2+incompatible":                   "28.5.2+incompatible",
		"v1.20.0-rc.3":                           "1.20.0-rc.3",
	}
	for in, want := range cases {
		if got := cleanGoVersion(in); got != want {
			t.Errorf("cleanGoVersion(%q) = %q, want %q", in, got, want)
		}
	}
}

// S4 Task 1: the PURL keeps the toolchain-shape version on tagged
// releases (purl-spec golang type), routes the `(devel)` marker into
// a `?vcs_ref=devel` qualifier so vulnerability scanners skip the
// row instead of treating "(devel)" as a version literal, and falls
// back to `@unknown` for empty inputs.
func TestPurlGolang(t *testing.T) {
	cases := []struct {
		modulePath, version, want string
	}{
		{"github.com/spf13/cobra", "v1.8.0", "pkg:golang/github.com/spf13/cobra@v1.8.0"},
		{"github.com/spf13/cobra", "", "pkg:golang/github.com/spf13/cobra@unknown"},
		{"example.com/local", "(devel)", "pkg:golang/example.com/local?vcs_ref=devel"},
		{"", "v1.0.0", ""},
	}
	for _, c := range cases {
		if got := purlGolang(c.modulePath, c.version); got != c.want {
			t.Errorf("purlGolang(%q, %q) = %q, want %q",
				c.modulePath, c.version, got, c.want)
		}
	}
}

// ─── ELF extractor ──────────────────────────────────────────────────

func TestELFExtractorRejectsNonELF(t *testing.T) {
	e := &ELFLibraryExtractor{}
	if e.Match(context.Background(), File{Body: []byte("MZ-pe-shape")}) {
		t.Error("ELF extractor should not match PE")
	}
}

func TestELFExtractorReturnsEmptyForBareELF(t *testing.T) {
	body := buildMinimalELF(t)
	id, err := (&ELFLibraryExtractor{}).Extract(context.Background(), File{
		Path: "opt/lib/x.so",
		Body: body,
	})
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if !id.IsEmpty() {
		t.Errorf("Identity = %+v, want empty (no SONAME, no build-id, no .rodata)", id)
	}
}

// S4 Task 0: an ELF binary with NO SONAME must yield empty Identity
// even when its filename looks like a `.so` library or a known busybox
// applet. Earlier revisions fell back to `basename(file.Path)`, which
// fabricated `pkg:generic/<basename>` rows on stripped binaries.
func TestELFExtractorNoBasenameFallbackWithoutSoname(t *testing.T) {
	body := buildMinimalELF(t) // no .dynamic section → no SONAME
	cases := []string{
		"opt/lib/libssl.so.3",      // looks like a library
		"usr/bin/busybox",          // a stripped multi-call binary
		"usr/local/bin/crypto",     // openssl helper basename
		"usr/local/bin/myfakebash", // busybox symlink target
		"usr/local/bin/c_rehash",   // openssl script wrapper
	}
	for _, p := range cases {
		t.Run(p, func(t *testing.T) {
			id, err := (&ELFLibraryExtractor{}).Extract(context.Background(), File{
				Path: p,
				Body: body,
			})
			if err != nil {
				t.Fatalf("Extract(%s): %v", p, err)
			}
			if !id.IsEmpty() {
				t.Errorf("Identity for %s = %+v, want empty (no SONAME)", p, id)
			}
		})
	}
}

func TestSonameToName(t *testing.T) {
	cases := map[string]string{
		"libsodium.so.23.3.0": "sodium",
		"libssl.so.3":         "ssl",
		"libc.so.6":           "c",
		"libfoo.so":           "foo",
		"baremod.so":          "baremod",
		"":                    "",
	}
	for in, want := range cases {
		if got := sonameToName(in); got != want {
			t.Errorf("sonameToName(%q) = %q, want %q", in, got, want)
		}
	}
}

// ─── Rust extractor ─────────────────────────────────────────────────

func TestRustExtractorAuditableSection(t *testing.T) {
	// Build a tiny ELF with a `.dep-v0` zlib-compressed JSON section.
	manifestJSON := `{
		"packages": [
			{"name": "rocket", "version": "0.5.0", "root": true},
			{"name": "tokio",  "version": "1.35.0"},
			{"name": "serde",  "version": "1.0.190"}
		]
	}`
	body := buildELFWithSection(t, ".dep-v0", zlibCompress(t, []byte(manifestJSON)))

	id, err := (&RustExtractor{}).Extract(context.Background(), File{Body: body})
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if id.Name != "rocket" || id.Version != "0.5.0" {
		t.Errorf("identity = %+v", id)
	}
	if id.PURL != "pkg:cargo/rocket@0.5.0" {
		t.Errorf("PURL = %q", id.PURL)
	}
	if len(id.SubComponents) != 2 {
		t.Errorf("SubComponents count = %d, want 2", len(id.SubComponents))
	}
	if id.Properties["rust.dep.count"] != "2" {
		t.Errorf("dep.count = %q", id.Properties["rust.dep.count"])
	}
}

func TestRustExtractorNoSection(t *testing.T) {
	body := buildMinimalELF(t)
	id, err := (&RustExtractor{}).Extract(context.Background(), File{Body: body})
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if !id.IsEmpty() {
		t.Errorf("Identity = %+v, want empty (no .dep-v0)", id)
	}
}

func TestRustExtractorBadZlib(t *testing.T) {
	body := buildELFWithSection(t, ".dep-v0", []byte("not-zlib"))
	_, err := (&RustExtractor{}).Extract(context.Background(), File{Body: body})
	if err == nil {
		t.Fatal("expected error for malformed zlib")
	}
}

// ─── Python extractor ───────────────────────────────────────────────

func TestPythonExtractorMatchesDistInfoMETADATA(t *testing.T) {
	e := &PythonExtractor{}
	if !e.Match(context.Background(), File{Path: "site-packages/requests-2.31.0.dist-info/METADATA"}) {
		t.Error("should match dist-info METADATA")
	}
	if e.Match(context.Background(), File{Path: "META-INF/MANIFEST.MF/METADATA"}) {
		t.Error("should NOT match METADATA outside dist-info")
	}
	if e.Match(context.Background(), File{Path: "etc/hostname"}) {
		t.Error("should not match unrelated paths")
	}
}

func TestPythonExtractorParsesMetadata(t *testing.T) {
	body := []byte(`Metadata-Version: 2.1
Name: requests
Version: 2.31.0
Summary: Python HTTP for Humans.
Author: Kenneth Reitz
License: Apache-2.0
Home-page: https://requests.readthedocs.io
Requires-Python: >=3.7

Long description follows here.
`)
	id, err := (&PythonExtractor{}).Extract(context.Background(), File{
		Path: "site-packages/requests-2.31.0.dist-info/METADATA",
		Body: body,
	})
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if id.Name != "requests" || id.Version != "2.31.0" {
		t.Errorf("identity = %+v", id)
	}
	if id.PURL != "pkg:pypi/requests@2.31.0" {
		t.Errorf("PURL = %q", id.PURL)
	}
	if id.Vendor != "Kenneth Reitz" {
		t.Errorf("Vendor = %q", id.Vendor)
	}
	if id.Properties["python.summary"] != "Python HTTP for Humans." {
		t.Errorf("summary = %q", id.Properties["python.summary"])
	}
	if id.Properties["python.license"] != "Apache-2.0" {
		t.Errorf("license = %q", id.Properties["python.license"])
	}
}

func TestPythonExtractorEmptyOnMissingName(t *testing.T) {
	body := []byte("Metadata-Version: 2.1\nVersion: 1.0\n")
	id, err := (&PythonExtractor{}).Extract(context.Background(), File{Body: body})
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if !id.IsEmpty() {
		t.Errorf("Identity = %+v, want empty", id)
	}
}

func TestPythonExtractorContinuationLines(t *testing.T) {
	body := []byte("Name: foo\nVersion: 1.0\nDescription: First line\n  continuation\n\n")
	headers := parseRFC822Headers(body)
	if headers["Name"] != "foo" {
		t.Errorf("Name = %q", headers["Name"])
	}
	if headers["Description"] != "First line continuation" {
		t.Errorf("Description = %q", headers["Description"])
	}
}

// ─── PE extractor ───────────────────────────────────────────────────

func TestPEExtractorRejectsNonPE(t *testing.T) {
	e := &PEExtractor{}
	if e.Match(context.Background(), File{Body: []byte{0x7f, 'E', 'L', 'F'}}) {
		t.Error("PE extractor should not match ELF")
	}
}

// S4 Task 0: the PE filename pattern (`name-1.2.3.exe`) was removed
// because the filename is not a verifiable identity. Without
// VS_VERSIONINFO parsing the extractor surfaces no Identity at all
// for well-formed PE files; the untracked enricher records them as
// observed-only.
func TestPEExtractorNoFilenameFallback(t *testing.T) {
	// A minimally valid PE that debug/pe will parse — just the MZ
	// magic followed by the PE header at offset 0x80. We don't need a
	// real binary; debug/pe.NewFile only requires the structure to be
	// walkable. If parsing fails the extractor returns empty too, so
	// either way the assertion holds.
	body := []byte{'M', 'Z'}
	id, err := (&PEExtractor{}).Extract(context.Background(), File{
		Path: "opt/myapp-1.2.3.exe",
		Body: body,
	})
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if !id.IsEmpty() {
		t.Errorf("Identity = %+v, want empty (filename fallback removed)", id)
	}
}

// ─── Helpers ────────────────────────────────────────────────────────

func buildJAR(t *testing.T, files map[string]string) []byte {
	t.Helper()
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	for name, body := range files {
		w, err := zw.Create(name)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := w.Write([]byte(body)); err != nil {
			t.Fatal(err)
		}
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

func zlibCompress(t *testing.T, body []byte) []byte {
	t.Helper()
	var buf bytes.Buffer
	zw := zlib.NewWriter(&buf)
	if _, err := zw.Write(body); err != nil {
		t.Fatal(err)
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

// buildMinimalELF returns a tiny but well-formed 64-bit ELF file
// with no sections beyond the SHT_NULL header. Enough to satisfy
// debug/elf.NewFile so extractors can probe sections without
// crashing.
func buildMinimalELF(t *testing.T) []byte {
	t.Helper()
	return buildELFWithSection(t, "", nil)
}

// buildELFWithSection returns an ELF64 file carrying ONE custom
// section with the given name and contents (when sectionName is
// "", the file has no custom section). Used for the Rust auditable
// fixture; deliberately bare-bones — just enough for debug/elf to
// parse and surface the section.
func buildELFWithSection(t *testing.T, sectionName string, sectionData []byte) []byte {
	t.Helper()

	const (
		ehSize = 64
		phSize = 0
		shSize = 64
	)

	// Section layout:
	//   [0] SHT_NULL
	//   [1] section .shstrtab
	//   [2] custom section (only when sectionName != "")
	hasCustom := sectionName != ""
	numSections := uint16(2)
	if hasCustom {
		numSections = 3
	}

	// Build .shstrtab — null + ".shstrtab\0" + (optional) "<sectionName>\0"
	var shstr bytes.Buffer
	shstr.WriteByte(0) // index 0 = empty string
	shstrtabNameOff := uint32(shstr.Len())
	shstr.WriteString(".shstrtab")
	shstr.WriteByte(0)
	customNameOff := uint32(0)
	if hasCustom {
		customNameOff = uint32(shstr.Len())
		shstr.WriteString(sectionName)
		shstr.WriteByte(0)
	}

	// Compute section file offsets. Section table follows the
	// data blob.
	dataStart := uint64(ehSize)
	shstrtabOffset := dataStart
	customOffset := uint64(0)
	cursor := shstrtabOffset + uint64(shstr.Len())
	if hasCustom {
		customOffset = cursor
		cursor += uint64(len(sectionData))
	}
	shoff := cursor

	// Total size = section table end.
	totalSize := int(shoff) + int(numSections)*shSize

	out := make([]byte, totalSize)

	// ELF header.
	copy(out[0:], []byte{0x7f, 'E', 'L', 'F'})
	out[4] = 2 // ELFCLASS64
	out[5] = 1 // ELFDATA2LSB
	out[6] = 1 // EV_CURRENT
	out[7] = 0 // OSABI System V
	// e_type=ET_DYN (3), e_machine=EM_X86_64 (62)
	binary.LittleEndian.PutUint16(out[16:], 3)
	binary.LittleEndian.PutUint16(out[18:], 62)
	binary.LittleEndian.PutUint32(out[20:], 1) // e_version
	// e_entry / e_phoff / e_shoff
	binary.LittleEndian.PutUint64(out[24:], 0)
	binary.LittleEndian.PutUint64(out[32:], 0)
	binary.LittleEndian.PutUint64(out[40:], shoff)
	binary.LittleEndian.PutUint32(out[48:], 0)           // e_flags
	binary.LittleEndian.PutUint16(out[52:], ehSize)      // e_ehsize
	binary.LittleEndian.PutUint16(out[54:], phSize)      // e_phentsize
	binary.LittleEndian.PutUint16(out[56:], 0)           // e_phnum
	binary.LittleEndian.PutUint16(out[58:], shSize)      // e_shentsize
	binary.LittleEndian.PutUint16(out[60:], numSections) // e_shnum
	binary.LittleEndian.PutUint16(out[62:], 1)           // e_shstrndx — index of .shstrtab

	// Section data.
	copy(out[shstrtabOffset:], shstr.Bytes())
	if hasCustom {
		copy(out[customOffset:], sectionData)
	}

	// Section headers.
	writeSectionHeader := func(idx int, nameOff uint32, typ uint32, off, size uint64) {
		base := int(shoff) + idx*shSize
		binary.LittleEndian.PutUint32(out[base+0:], nameOff)
		binary.LittleEndian.PutUint32(out[base+4:], typ)
		binary.LittleEndian.PutUint64(out[base+8:], 0)  // flags
		binary.LittleEndian.PutUint64(out[base+16:], 0) // addr
		binary.LittleEndian.PutUint64(out[base+24:], off)
		binary.LittleEndian.PutUint64(out[base+32:], size)
		binary.LittleEndian.PutUint32(out[base+40:], 0) // link
		binary.LittleEndian.PutUint32(out[base+44:], 0) // info
		binary.LittleEndian.PutUint64(out[base+48:], 1) // addralign
		binary.LittleEndian.PutUint64(out[base+56:], 0) // entsize
	}
	writeSectionHeader(0, 0, 0 /*SHT_NULL*/, 0, 0)
	writeSectionHeader(1, shstrtabNameOff, uint32(elf.SHT_STRTAB), shstrtabOffset, uint64(shstr.Len()))
	if hasCustom {
		writeSectionHeader(2, customNameOff, uint32(elf.SHT_PROGBITS), customOffset, uint64(len(sectionData)))
	}

	// Sanity: parse our own output to catch obviously wrong shapes
	// before the test's real assertions trip.
	if _, err := elf.NewFile(bytes.NewReader(out)); err != nil {
		t.Fatalf("buildELFWithSection produced invalid ELF: %v", err)
	}
	return out
}

// silence the unused-import warning for builds that don't reach the
// Rust test path.
var _ = strings.Contains
